### ISSUE TITLE
之前的论文速递呢？

### ISSUE THREAD

**Issue by abcdvzz** [amusi/daily-paper-computer-vision#1]
这个是最近才有的是吗，请问之前的论文速递可以整理一下上传到这里吗，感谢您的付出。

**Comment by amusi** [comment]
你好，之前的论文速递没有整理到这个github上，而是发布在我的微信公众号上了（一直有更新）。这个daily-paper-computer-vision是最近才整理的，暂时不打算把以前整理的paper同步到着，只会更新以后的。如果你想了解之前的论文速递信息，可以关注CVer微信公众号，即微信搜索CVer即可。
